version: '3.5'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      mynet:
        ipv4_address: 172.16.0.2
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      mynet:
        ipv4_address: 172.16.0.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
volumes:
  pgdata: