"""empty message

Revision ID: 468a1d683c21
Revises: 
Create Date: 2019-03-13 18:19:43.941367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468a1d683c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=True),
    sa.Column('twitch_login_name', sa.String(), nullable=True),
    sa.Column('twitch_display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
