"""empty message

Revision ID: 69aaa8c3fcbe
Revises: 73b095888f8a
Create Date: 2019-03-24 20:41:53.953263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69aaa8c3fcbe'
down_revision = '73b095888f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('current_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    new_column = sa.table('participants', sa.column('current_points'))
    op.execute(new_column.update().values(**{'current_points': 0}))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'current_points')
    # ### end Alembic commands ###
